# Analysis options for custom_lint_rules package
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: true
