name: {{library_name.snakeCase()}}
description: {{library_name.pascalCase()}} library package for Fishbowl app.
version: 0.0.1
publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
  test: